// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAi_U1oSpbQtIyTK-_dvOeBDwqpFAoQtwU',
    appId: '1:438087012253:web:854202411d4ef08a8e2974',
    messagingSenderId: '438087012253',
    projectId: 'face-detection-1883d',
    authDomain: 'face-detection-1883d.firebaseapp.com',
    storageBucket: 'face-detection-1883d.firebasestorage.app',
    measurementId: 'G-3V5SD7ZMYM',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARIgtAYdmzuKsIguHcggXcbmOZxeFXPRg',
    appId: '1:438087012253:ios:48ab441c8408bf0a8e2974',
    messagingSenderId: '438087012253',
    projectId: 'face-detection-1883d',
    storageBucket: 'face-detection-1883d.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARIgtAYdmzuKsIguHcggXcbmOZxeFXPRg',
    appId: '1:438087012253:ios:48ab441c8408bf0a8e2974',
    messagingSenderId: '438087012253',
    projectId: 'face-detection-1883d',
    storageBucket: 'face-detection-1883d.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAi_U1oSpbQtIyTK-_dvOeBDwqpFAoQtwU',
    appId: '1:438087012253:web:8b42149dd11c7b948e2974',
    messagingSenderId: '438087012253',
    projectId: 'face-detection-1883d',
    authDomain: 'face-detection-1883d.firebaseapp.com',
    storageBucket: 'face-detection-1883d.firebasestorage.app',
    measurementId: 'G-SJHWG7J99S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7dZfZNFT4pkqxCHQZMYfF34ocXxVLzzk',
    appId: '1:438087012253:android:37dc5a38ecd249df8e2974',
    messagingSenderId: '438087012253',
    projectId: 'face-detection-1883d',
    storageBucket: 'face-detection-1883d.firebasestorage.app',
  );
}
